-- ==========================================
-- 1. DDL: Create database
-- ==========================================
CREATE DATABASE IF NOT EXISTS employeesdb;

-- ==========================================
-- 2. Use database
-- ==========================================
USE employeesdb;

-- ==========================================
-- 3. Create tables (employee, department)
-- ==========================================
-- Create Employee Table
CREATE TABLE employee (
    id CHAR(36) PRIMARY KEY,            -- used to store uuid, generated by MySQL calling function UUID()
    first_name VARCHAR(50) NOT NULL,
    last_name VARCHAR(50) NOT NULL,
    email VARCHAR(100) UNIQUE NOT NULL,
    dept_id INT NULL
);

-- ALTER TABLE employee MODIFY COLUMN id BINARY(16) NOT NULL; 
-- ALTER TABLE employee ALTER COLUMN id DROP DEFAULT; 

CREATE TABLE department (
    id INT PRIMARY KEY AUTO_INCREMENT,
    dept_name VARCHAR(50)
);

-- ==========================================
-- 2. DML: Insert 10 Records Total
-- ==========================================
-- Insert Departments
INSERT INTO department (id, dept_name) VALUES 
(1, 'Engineering'), 
(2, 'Sales'), 
(3, 'HR'), 
(4, 'Marketing');

-- Insert Employees (UUID function invoked per employee id)
INSERT INTO employee (id, first_name, last_name, email, dept_id) VALUES 
(UUID(), 'Alice', 'Johnson', 'alice.johnson@example.com', 1),
(UUID(), 'Bob', 'Smith', 'bob.smith@example.com', 2),
(UUID(), 'Diana', 'Prince', 'diana.prince@example.com', 3),
(UUID(), 'Charlie', 'Davis', 'charlie.davis@example.com', 1),
(UUID(), 'Edward', 'Norton', 'edward.norton@example.com', 2),
(UUID(), 'Frank', 'Holmes', 'frank.holmes@example.com', NULL);  -- No department

-- ==========================================
-- 3. SQL JOIN EXAMPLES 
-- Diagram reference: https://i.sstatic.net/1UKp7.png
-- Additional reference: https://medium.com/@eshanpurekar/my-dbms-journey-part-3-types-of-joins-and-set-operations-in-mysql-c16f1badacac
-- ==========================================


-- FULL JOIN (Everything from both tables)
-- Q: Show all employees and all departments. 
SELECT e.*, d.*
FROM employee e LEFT JOIN department d
ON e.dept_id = d.id
UNION
SELECT e.*, d.*
FROM employee e RIGHT JOIN department d
ON e.dept_id = d.id;

-- FULL JOIN EXCLUDING INTERSECTION (Unique to A or B)
-- Q: Show employees who are NOT assigned to any department AND departments that have NO employees assigned to them.
SELECT * FROM employee e LEFT JOIN department d on e.dept_id = d.id -- Frank Holmes (unique part of Set A)
WHERE d.id IS NULL
UNION
SELECT * FROM employee e RIGHT JOIN department d on e.dept_id = d.id -- Marketing (unique part of Set B)
WHERE e.dept_id IS NULL;

-- LEFT JOIN (Everything from Table A)
-- Q: Show all employees, regardless of whether they belong to a department. 
SELECT employee.first_name, employee.last_name, department.dept_name
FROM employee LEFT JOIN department
ON employee.dept_id = department.id;

-- LEFT JOIN EXCLUDING INTERSECTION (Only in Table A)
-- Q: Show only the employees who are NOT assigned to any department. 
SELECT employee.first_name, employee.last_name, department.dept_name
FROM employee LEFT JOIN department
ON employee.dept_id = department.id
WHERE department.id IS NULL;

-- RIGHT JOIN (Everything from Table B)
-- Q: Show all departments, regardless of whether they have employees.
SELECT department.dept_name, employee.first_name, employee.last_name
FROM employee RIGHT JOIN department ON employee.dept_id = department.id;

SELECT department.dept_name, COUNT(employee.id) AS `Number of Staff`
FROM employee RIGHT JOIN department ON employee.dept_id = department.id
GROUP BY department.dept_name;

-- INNER JOIN (Intersection of A and B)
-- Q: Show only employees assigned to departments AND only departments that have employees.
SELECT employee.first_name, employee.last_name, department.dept_name
FROM employee INNER JOIN department
ON employee.dept_id = department.id;